Make the error on other task message red
science-computing/butido pull request #404
Opened 2024-08-13 13:45 UTC by ammernico

Will make it easier to spot it in the output.

Partially fixes #57

This is an older commit. CP tested it, was fine

2024-08-13 16:06 UTC, primeos-work requested changes
Looks fine to me but you shouldn't use `Partially fixes #57` in the commit message if the issue should remain open (which I assume it should if this only partially fixes it) as that would close it automatically (s. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests for details).

You should still reference #57 though - just make sure there isn't a keyword that closes the issue right in front of it ;)

Does this really help with #57 though? That issue is about which job/dependency triggered the "error on other task" and I though we didn't want to color these inherited/propagated error messages red (for "error occurred" it should be fine and for "error on other task" yellow/orange/etc. could perhaps make sense?).

And is it intentional that you use your Atos email address in the commit metadata and trailer?: `Signed-off-by: Nico Steinle <nico.steinle@atos.net>`

2024-08-13 16:06 UTC, primeos-work commented on src/orchestrator/orchestrator.rs
> +                "error occured".red()
Why change "occurred" to "occured"?
https://writer.com/blog/occurred-occured/
(I (hopefully) fixed that as part of 53de218d1941c3ecd45c623e7570e9eb8ff3d83c...)

2024-08-14 09:59 UTC, ammernico commented
(because it's red (like in occured))

No, it was an old commit and disregarded all changes made in since the commit was created.
Let's see what CP thinks about the coloring

2024-09-12 09:19 UTC, closed without merging

2024-10-01 20:41 UTC, christophprokop commented
output much better readable since 71b1921