Dot graph
science-computing/butido pull request #407
Opened 2024-08-19 09:59 UTC by ammernico

2024-08-21 13:12 UTC, christophprokop commented
Much easier to read and grasp now. Thank you!
`"gcc-14.2.0"` without the quotes would be even cleaner: `gcc-14.2.0`
I forgot that yesterday. Sorry!

2024-08-28 13:17 UTC, primeos-work requested changes
Overall it LGTM but we can still tweak a few details. Please also update the PR title and description.

2024-08-28 13:17 UTC, primeos-work commented on src/commands/tree_of.rs
> +                &|_, nr| format!("color = {} ", get_edge_color(nr.weight())).to_string(),
We could perhaps consider using dashed lines for build dependencies (as they're only required temporarily during compile time) to make it a bit more intuitive?
What do you think @christophprokop?

2024-08-28 13:17 UTC, primeos-work commented on src/commands/tree_of.rs
> +            let petgraph = convert_dag_to_petgraph(dag.unwrap());
We can probably use the following instead (seems a bit cleaner than `unwrap`):
```
package_dags
        .and_then_ok(|dag| {
```

2024-08-28 13:17 UTC, primeos-work commented on src/package/package.rs
> +        format!("{}-{}", self.name, self.version)
I'd personally prefer a "{name} {version}" as format as the version might contain dashes but shouldn't contain spaces - what do you think?

2024-08-28 13:51 UTC, primeos-work commented on src/cli.rs
> +                .help("Create a dot graph")
Or even better: Something like "Output the dependency DAG in the Graphviz DOT format"

2024-09-11 19:50 UTC, primeos-work approved these changes
LGTM now, thanks :)

There was a conflict in `Cargo.toml` so I did a rebase and took the liberty to make a minor edit to the commit message subject while I'm at it (:P). I also decided to add a second commit to keep the overall PR diff cleaner.

I ran a test and the results seem/render fine. We could name the graphs when outputting multiple DOT graphs but the tools I tested couldn't handle multiple graphs at once anyway (subgraphs would be fine but I guess, for now, we don't really need multiple graphs anyway and could always have another look at this later).

2024-09-11 19:57 UTC, merged